version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dannybase_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dannybase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dannybase"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: dannybase_web
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env

volumes:
  postgres_data: